apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 250m
              memory: 64Mi
  replicas: 3
  selector:
    matchLabels:
      app: myapp
