apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 250m
          memory: 64Mi
