apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: test
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 250m
              memory: 64Mi
  replicas: 3
  selector:
    matchLabels:
      app: myapp
